### ISSUE TITLE
运行了一下，好像还没开发完吗，用不了

### ISSUE THREAD

**Issue by oit63** [4faramita/ShadowsocksX-NG-R8-Updater#1]

**Comment by oit63** [comment]
发现了，作者把自己账号名字换了。。https://github.com/qinyuhang/ShadowsocksX-NG-R/releases

**Comment by oit63** [comment]
这个 js 程序挺好玩的，：）

**Comment by 4faramita** [comment]
作者删掉了上游代码，并且不再建议继续使用，这个脚本暂时废弃不再维护。建议转向 ShadowsocksX-NG

**Comment by oit63** [comment]
我刚看了下，还在更新啊。
